### ISSUE TITLE
Allowing users to write their own serializer

### ISSUE THREAD

**Issue by Aparnarr** [pravega/pravega-serializer#5]
`     EventStreamWriter<String> writer = clientFactory.createEventWriter(streamName,
                                                      new JavaSerializer<String>(),`
Tom's Comment:

This isn't (JavaSerializer) a great pattern. We have a UTF8StringSerializer which is specific to strings and is better for them. Java serialize is a basic fallback for any other random Java object that you don't want to write a serializer for. In general many users will want to write serializes or use our Json and Avro serializes which are located here: https://github.com/pravega/pravega-serializer

**Comment by shrids** [comment]
This issue needs to be moved to pravega-samples.
